// ── lib/models/agent_decision.dart ──────────────────────────────────
//
// Open-source integrations
// • rivian/ai-sast  (Apache 2.0)  — alertId for feedback loop
// • rivian/odxtools (MIT)         — OBD-II dtcCode + VRS cvssScore/cvssVector
// • NATS subject routing          — subject field from server payload

import 'package:flutter/material.dart';

enum DecisionType {
  priorityAlert,
  batteryWarming,
  batteryWarning,
  statusReport,
  rangeEstimate,
  maintenanceStatus,
  normal;

  static DecisionType fromString(String s) {
    switch (s) {
      case 'PRIORITY_ALERT':     return DecisionType.priorityAlert;
      case 'BATTERY_WARMING':    return DecisionType.batteryWarming;
      case 'BATTERY_WARNING':    return DecisionType.batteryWarning;
      case 'STATUS_REPORT':      return DecisionType.statusReport;
      case 'RANGE_ESTIMATE':     return DecisionType.rangeEstimate;
      case 'MAINTENANCE_STATUS': return DecisionType.maintenanceStatus;
      default:                   return DecisionType.normal;
    }
  }
}

enum Severity {
  info,
  warning,
  critical;

  static Severity fromString(String s) {
    switch (s.toUpperCase()) {
      case 'CRITICAL': return Severity.critical;
      case 'WARNING':  return Severity.warning;
      default:         return Severity.info;
    }
  }
}

/// Operator feedback status — mirrors rivian/ai-sast store_feedback() statuses.
enum AlertFeedback { none, confirmed, falsePositive }

class AgentDecision {
  final String agentName;
  final DecisionType decisionType;
  final String message;
  final Severity severity;
  final double timestamp;
  final Map<String, dynamic> metadata;

  // ── rivian/ai-sast feedback loop ─────────────────────────────────
  /// 8-char SHA-1 hex ID, unique per alert (generated by server).
  final String alertId;

  // ── rivian/odxtools OBD-II / DTC fields ──────────────────────────
  /// OBD-II Diagnostic Trouble Code (e.g. P0218, P1A00, U1001).
  final String dtcCode;

  /// Vehicle Risk Score 0–10 (CVSS-inspired, computed by server).
  final double cvssScore;

  /// VRS vector string (e.g. "VRS:1.0/AV:Motor/AC:H/MS:C/SI:H/CI:H").
  final String cvssVector;

  /// NATS-style subject field for future routing (rivian/nats-server pattern).
  final String subject;

  /// Operator feedback state — set locally after FEEDBACK_RESULT received.
  final AlertFeedback feedback;

  const AgentDecision({
    required this.agentName,
    required this.decisionType,
    required this.message,
    required this.severity,
    required this.timestamp,
    required this.metadata,
    this.alertId    = '',
    this.dtcCode    = '',
    this.cvssScore  = 0.0,
    this.cvssVector = '',
    this.subject    = '',
    this.feedback   = AlertFeedback.none,
  });

  factory AgentDecision.fromJson(Map<String, dynamic> json) => AgentDecision(
        agentName:    json['agent_name']    as String? ?? '',
        decisionType: DecisionType.fromString(json['decision_type'] as String? ?? ''),
        message:      json['message']       as String? ?? '',
        severity:     Severity.fromString(json['severity'] as String? ?? 'INFO'),
        timestamp:    (json['timestamp'] as num?)?.toDouble() ?? 0.0,
        metadata:     Map<String, dynamic>.from(json['metadata'] as Map? ?? const {}),
        alertId:      json['alert_id']      as String? ?? '',
        dtcCode:      json['dtc_code']      as String? ?? '',
        cvssScore:    (json['cvss_score']   as num?)?.toDouble() ?? 0.0,
        cvssVector:   json['cvss_vector']   as String? ?? '',
        subject:      json['subject']       as String? ?? '',
      );

  /// Returns a copy with updated [feedback].
  AgentDecision withFeedback(AlertFeedback fb) => AgentDecision(
        agentName:    agentName,
        decisionType: decisionType,
        message:      message,
        severity:     severity,
        timestamp:    timestamp,
        metadata:     metadata,
        alertId:      alertId,
        dtcCode:      dtcCode,
        cvssScore:    cvssScore,
        cvssVector:   cvssVector,
        subject:      subject,
        feedback:     fb,
      );

  // ── display helpers ───────────────────────────────────────────────

  String get agentLabel {
    switch (agentName) {
      case 'AnomalyDetectionAgent':      return 'Anomaly Detection';
      case 'ContextAwarePlannerAgent':   return 'Context Planner';
      case 'VehicleStatusReporterAgent': return 'AI Status Reporter';
      case 'RangePredictionAgent':       return 'Range Prediction';
      case 'PredictiveMaintenanceAgent': return 'Predictive Maintenance';
      default: return agentName;
    }
  }

  IconData get agentIcon {
    switch (agentName) {
      case 'AnomalyDetectionAgent':      return Icons.analytics_rounded;
      case 'ContextAwarePlannerAgent':   return Icons.thermostat_rounded;
      case 'VehicleStatusReporterAgent': return Icons.smart_toy_rounded;
      case 'RangePredictionAgent':       return Icons.route_rounded;
      case 'PredictiveMaintenanceAgent': return Icons.health_and_safety_rounded;
      default: return Icons.device_hub_rounded;
    }
  }

  /// Colour-coded DTC prefix:  P = powertrain, U = network, B = body.
  String get dtcSystem {
    if (dtcCode.startsWith('P')) return 'Powertrain';
    if (dtcCode.startsWith('U')) return 'Network';
    if (dtcCode.startsWith('B')) return 'Body';
    return 'Unknown';
  }

  bool get hasDtc     => dtcCode.isNotEmpty;
  bool get hasVrs     => cvssScore > 0.0;

  bool get isPriorityAlert     => decisionType == DecisionType.priorityAlert;
  bool get isBatteryWarming    => decisionType == DecisionType.batteryWarming;
  bool get isStatusReport      => decisionType == DecisionType.statusReport;
  bool get isRangeEstimate     => decisionType == DecisionType.rangeEstimate;
  bool get isMaintenanceStatus => decisionType == DecisionType.maintenanceStatus;
}
